### PR TITLE
All tests can be run from root path

### PR DESCRIPTION
**Pull request by Xierumeng**
No need to use `cd path/to/directory` . `pytest` and `python -m path.to.file` work.

### CODE REVIEW

**Comment by Xierumeng** [comment]
Could not test `comms/` due to lack of hardware.

**Review by Trotyl15 — APPROVED** [review]
LGTM.

**Comment by Trotyl15** [comment]
> Could not test `comms/` due to lack of hardware.

Do you want to test it before merge?

**Comment by Xierumeng** [comment]
It's not particularly important because we are not using it.

**Pull request merged**
